### ISSUE TITLE
--gas-price

### ISSUE THREAD

**Issue by msanlisavas** [make-software/casper-account-info-contract#13]
When running the command from provided docs:
```
sudo -u casper casper-client put-deploy \
    --chain-name "casper" \
    --node-address "http://127.0.0.1:7777/" \
    --secret-key "/etc/casper/validator_keys/secret_key.pem" \
    --session-hash "fb8e0215c040691e9bbe945dd22a00989b532b9c2521582538edb95b61156698" \
    --session-entry-point "set_url" \
    --payment-amount 10000000000 \
    --gas-price=1 \
    --session-arg=url:"string='https://MYSUPERCASPERVALIDATOR.COM'"
```
I get the error: 

error: unexpected argument '--payment-gas-price' found

Also its usage prompt is: 

Usage: casper-client put-deploy --chain-name <NAME> --node-address <HOST:PORT> --secret-key <PATH> --session-entry-point <NAME> <--session-path <PATH>|--session-package-hash <HEX STRING>|--session-package-name <NAME>|--is-session-transfer|--session-hash <HEX STRING>|--session-name <NAME>|--show-simple-arg-examples|--show-json-args-examples> <--payment-amount <AMOUNT>|--payment-path <PATH>|--payment-package-hash <HEX STRING>|--payment-package-name <NAME>|--payment-hash <HEX STRING>|--payment-name <NAME>|--show-simple-arg-examples|--show-json-args-examples> <--payment-arg <"NAME:TYPE='VALUE'" OR "NAME:TYPE=null">|--payment-args-json <JSON ARRAY>|--payment-args-complex <PATH>>

I think its removed and the docs are not up to date. Running it without --gas-price worked.

**Comment by mrkara** [comment]
@msanlisavas Thanks a lot for yoru contribution! The instructions have been updated.
